### ISSUE TITLE
Question: How do I scale this without changing the viewport?

### ISSUE THREAD

**Issue by jgandert** [kotcrab/vis-ui-contrib#10]
Sorry, if this doesn't belong here. ~~I'd like to scale this skin without changing the viewport, since, as far as I know, the viewport needs to have a high resolution so that animations are fluid. (Otherwise it seems to jump from pixel to pixel so to speak which is very jarring.)~~ Oops.. apparently my font was set to "useIntegerPositions". I'd be still interested how one scales the theme up.. Is it as simple as multiplying most values in the `skin.json`?

Also, I'd like to remove the font from the skin, because I'm using [FreeTypeFontGenerator](https://github.com/libgdx/libgdx/wiki/Gdx-freetype) to generate the Bitmap font on the fly. Is it as easy as removing "droid-sans-13.png" and regenerating the atlas?

Thank you for creating this skin! :)

**Comment by BeppeMarnell** [comment]
When you call "VisUI.load(VisUI.SkinScale.X1)" for instance, instead of SkinScale.X1 you will use SkinScale.X2, it will scale automatically.

**Comment by jgandert** [comment]
@BeppeMarnell Ah, forgot this existed. Thanks! The way I had solved it was by indeed using a different viewport for the UI, which I think makes sense. (Though `SkinScale.X2` might be enough for some games.)
