### ISSUE TITLE
Create Gradle project for skins

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-ui-contrib#3]
Add a Gradle project to `skins` folder that could automate `JSON` generation from `USL` and packing of textures into atlases. Unify skin project structures: separate raw assets (`raw/x1` + `raw/x2` dirs?) from compiled and packed skins (`x1` + `x2` dirs?). Add `pack` (textures), `skin` (`USL`) and `compile` (combined) tasks, which should not fail if any of the folders or files are missing.

**Comment by czyzby** [comment]
Currently you cannot run the tasks on a single project. Even if you want to work on just one skin, as soon as you use `gradle compile`, you regenerate data for the others - resulting in uncommitted changes. I think it would make sense to use Gradle multi-project setup, with `skins` as the root folder.

**Comment by kotcrab** [comment]
Done, now you can do `gradle :tinted:compile` etc.
