### ISSUE TITLE
GWT module

### ISSUE THREAD

**Issue by czyzby** [kotcrab/vis-ui-contrib#5]
It seems that `vis-ui-contrib` library lacks GWT module definition.

**Comment by kotcrab** [comment]
`vis-ui-contrib` isn't really GWT compatible. There is only one class (`Pin`) that would work on GWT.

**Comment by czyzby** [comment]
And RegExodus highlight. ; )

**Comment by czyzby** [comment]
OK, up to you. Since there's no pattern-based highlighter for GWT, I'd go with at least partial GWT support for vis-ui-contrib, but it's not mandatory (I think).
