### ISSUE TITLE
Font file for the font used by tixel

### ISSUE THREAD

**Issue by LennartH** [kotcrab/vis-ui-contrib#6]
I recently *borrowed* your great skin tixel for my project. But the used font is too small for my application and scaling it with floating-point numbers results in ugly artifacts. Scaling with integers looks good, but *x2* is already to big.

Do you have the font file (e.g. *.ttf*) of the used font, so that I can generate my own Bitmap Font that fulfills my needs.

**Comment by czyzby** [comment]
I believe this is the [Ubuntu Light](http://font.ubuntu.com/) or [Droid Sans](https://fonts.google.com/specimen/Droid+Sans) font. Not sure if it will look so pixely when resized though.

**Comment by LennartH** [comment]
Yes the pixel look is the main issue. I also found the Droid Sans font, but it doesn't look as pixely as the Bitmap Font in the raw files. Did you do anything special when you generated the Bitmap Font?

**Comment by czyzby** [comment]
I honestly don't remember, I might have deleted all pixels that were not pure white in Gimp (select by color with 0% tolerance, invert selection, delete).

**Comment by LennartH** [comment]
Hmm ok. Sounds exhausting to do this by hand, but it's a way to pixelate a font. Thanks anyway.

The quest to find the perfect font continues.

**Comment by czyzby** [comment]
I'm pretty sure you could automate such task using Imagemagick or some other command line tool for processing images. Even a pure ~~Java tool~~ Groovy Gradle task using `BufferedImage` API would be trivial to write: iterate over all pixels, replace all non-white ones with transparency. A few lines, really.

**Comment by LennartH** [comment]
Yes, I thought the same, but I played around with the Image in Paint.NET and filtering by absolute white (#FFFFFFFF) leaves only a few pixels. You have to define a minimum alpha until a pixel is kept in the pixelated skin.

I implemented a gradle task that automatically pixelates a set of fonts. It's not that trivial, but it's bloated to support different families and different sizes and it's optimized, since it only operates on PNGs:
```gradle
ext {
    rawFontRoot = '../assets-raw/font/'
    fontsToPixelate = [
        ['droid-sans', [
                ['18', '#FFFFFF', 0.5 * 255],
                ['21', '#FFFFFF', 0.6 * 255],
                ['28', '#FFFFFF', 0.65 * 255]
            ]
        ]
    ]
}

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import javax.imageio.ImageIO;
task pixelateFonts (group: 'build') {
    description = 'Pixelates the defined fonts in the raw assets.'
    doLast {
        for (Object[] fontFamily : fontsToPixelate) {
            String familyName = fontFamily[0]
            String familyPath = rawFontRoot + familyName + '/'
            String pixelatedFamilyName = familyName + '-pixelated'
            String pixelatedFamilyPath = rawFontRoot + pixelatedFamilyName + '/'
            println 'Pixelating font family ' + familyName
            for (Object[] font : fontFamily[1]) {
                String fontSize = font[0]
                Color filter = Color.decode(font[1])
                Color transparent = new Color(0, true)
                double minAlpha = font[2]
                
                String fontPath = familyPath + 'fnt-' + fontSize + '/'
                String pixelatedFontPath = pixelatedFamilyPath + 'fnt-' + fontSize + '/'
                println '  Pixelating font fnt-' + fontSize + ':' + fontPath + ' -> ' + pixelatedFontPath
                
                String bitmapPath = fontPath + familyName + '-' + fontSize + '.png'
                BufferedImage bitmap = ImageIO.read(new File(bitmapPath))
                byte[] pixels = ((DataBufferByte) bitmap.getRaster().getDataBuffer()).getData()
                int x = 0;
                int y = 0;
                for (int pixelStart = 0; pixelStart < pixels.length; pixelStart += 4) {
                    int value = (((int) pixels[pixelStart] & 0xFF) << 24)     |  // alpha
                                (((int) pixels[pixelStart + 3] & 0xFF) << 16) |  // red
                                (((int) pixels[pixelStart + 2] & 0xFF) << 8)  |  // green
                                (((int) pixels[pixelStart + 1] & 0xFF) << 0);    // blue
                    Color color = new Color(value, true)
                    
                    if (color.getRed() == filter.getRed() &&
                        color.getGreen() == filter.getGreen() &&
                        color.getBlue() == filter.getBlue() &&
                        color.getAlpha() >= minAlpha) {
                            bitmap.setRGB(x, y, filter.getRGB())
                    } else {
                        bitmap.setRGB(x, y, transparent.getRGB())
                    }
                    
                    x++;
                    if (x == bitmap.getWidth()) {
                        x = 0;
                        y++;
                    }
                }
                
                String fntPath = fontPath + familyName + '-' + fontSize + '.fnt'
                copy {
                    from fntPath
                    into pixelatedFontPath
                    rename(familyName + '-' + fontSize + '.fnt',
                           pixelatedFamilyName + '-' + fontSize + '.fnt')
                }
                String pixelatedBitmapPath = pixelatedFontPath + pixelatedFamilyName + '-' + fontSize + '.png'
                ImageIO.write(bitmap, 'png', new File(pixelatedBitmapPath))
            }
        }
    }
}
```

**Comment by czyzby** [comment]
You could also try looking for fonts that are [pixelated by design](http://www.dafont.com/runescape-uf.font).

**Comment by LennartH** [comment]
I did, but I couldn't find one that satisfied me. Your suggestion is the best by now, but it doesn't really fit. Most pixelated fonts are quite bulky and that doesn't fit my UI scheme.

I like that the tixel font is lean, but still pixelated. I don't know what you did to create it, but you did it pretty good.
