### ISSUE TITLE
Windows thumbnail viewer sometimes can't be linked

### ISSUE THREAD

**Issue by WickedShell** [kotcrab/vis-ui-contrib#9]
On some windows machines when trying to open a file chooser the WinThumbnails.dll can't be found. This is only used if the check for supported machine passed. This isn't occurring on any of my windows machines, but on a users machine that is running windows 10, 64 bit, with Java 1.8.0_121

```
2017-05-14 20:08:06:0133 ERROR Thread[LWJGL Application,5,main]
  Stack trace:com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: C:\Users\user\AppData\Local\Temp\vne\4033840315\win32\WinThumbnails.dll: Can't find dependent libraries
    com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
```

**Comment by kotcrab** [comment]
The right repo would be https://github.com/kotcrab/vne/

I think this is related to VC redist package not being installed.  Can you verify if user doesn't have it installed? Probably version 2015 since it's compiled with Visual Studio 2015.

If that's the case I can recompile dll with it statically linked. It will make dll bigger of course.

**Comment by WickedShell** [comment]
Ah sorry, wasn't sure where to open it. How do I have them check if the VC redist package is present or not?

**Comment by kotcrab** [comment]
'Add or remove programs' window, search for Microsoft Visual C++ 2015.

**Comment by WickedShell** [comment]
They have "Visual c++ 2015 redistributable x64" installed.

**Comment by kotcrab** [comment]
Right, I forgot there are two versions . Judging by the dll loaded (`win32`) they would need x86 version. This confirms my theory, I'll look how to compile it without need for it.

**Comment by kotcrab** [comment]
Try vne-win-thumbnails 0.0.2-SNAPSHOT. It has dll recompiled in mode that should run without VC redist package installed. Let me know if it works, I'll do release.

**Comment by kotcrab** [comment]
Confirmed that missing VC redist was causing this issue and also confirmed that fix works. Released vne 1.0.0

**Comment by WickedShell** [comment]
@kotcrab sorry I hadn't gotten a chance to getting back to testing this yet...

**Comment by kotcrab** [comment]
No problem, I realized I have VM without VC installed so I was able to test
